version: "3.8"

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  rails:
    build:
      context: ./platform
      dockerfile: Dockerfile
    command: bash -c "
      ./bin/docker-entrypoint &&
      rm -f tmp/pids/server.pid &&
      bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./platform:/rails
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres@db:5432/platform_development
      REDIS_URL: redis://redis:6379/1
      RAILS_ENV: development

volumes:
  postgres_data:
