#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../../../config/application"
require "temporal/worker"

# Load the Rails environment
Rails.application.require_environment!

namespace = ARGV[0] || "polymetrics-dev"
description = ARGV[1]

begin
  Temporal.register_namespace(namespace, description)
  Temporal.logger.info "Namespace created", { namespace: namespace }
rescue Temporal::NamespaceAlreadyExistsFailure
  Temporal.logger.info "Namespace already exists", { namespace: namespace }
end

start_time = Time.current
timeout = 300 # 5 minutes

loop do
  if Time.current - start_time > timeout
    Temporal.logger.error("Namespace creation timeout", { namespace: namespace })
    exit 1
  end

  Temporal.list_custom_search_attributes(namespace: namespace)
  Temporal.logger.info("Namespace is ready", { namespace: namespace })
  break
rescue GRPC::NotFound
  Temporal.logger.info("Namespace not yet found, waiting and retrying", { namespace: namespace })
  sleep 1
  next
end
