#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../../../config/application"
require "temporal/worker"

# Load the Rails environment
Rails.application.require_environment!

worker = Temporal::Worker.new

worker.start
