require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/migrate/20240726225157_devise_token_auth_create_users.rb'
    
  TargetRubyVersion: 3.2

Style/Documentation:
  Enabled: false
  
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    -  'config/environments/development.rb'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/QuotedSymbols:
  EnforcedStyle: double_quotes

RSpec/DescribedClass:
  Enabled: false

RSpec/ExampleLength:
  Max: 25

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleMemoizedHelpers:
  Max: 15

Style/HashSyntax:
  EnforcedShorthandSyntax: never

RSpec/VerifiedDoubleReference:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Layout/LineLength:
  Max: 150

RSpec/MessageSpies:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false