connectors:
  - name: Github
    integration_type: api
    language: ruby
    class_name: github
    operations:
      - connect
      - read
      - write
    definition_status: certified
    version: 1.0.0
    maintainer: Polymetrics
  - name: DuckDB
    integration_type: database
    language: ruby
    class_name: duckdb
    operations:
      - connect
      - write
      - query
    definition_status: certified
    version: 1.0.0
    maintainer: Polymetrics
  - name: PostgreSQL
    integration_type: database
    language: javascript
    class_name: postgresql
    operations:
      - connect
      - write
      - query
    definition_status: coming_soon
    version: 1.0.0
    maintainer: Polymetrics
  - name: Salesforce CRM
    integration_type: api
    language: javascript
    class_name: salesforce_crm
    operations:
      - connect
      - read
    definition_status: coming_soon
    version: 1.0.0
    maintainer: Polymetrics