name: Rails CI/CD

on:
  pull_request:
    branches: [main]
    paths:
      - "platform/**"
  push:
    branches: [main]
    paths:
      - "platform/**"

jobs:
  rubocop-rspec:
    runs-on: ubuntu-22.04
    env:
      RAILS_ENV: test
      BUNDLE_GEMFILE: ${{ github.workspace }}/platform/Gemfile
      DATABASE_HOST: localhost
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    defaults:
      run:
        working-directory: platform
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0
          bundler-cache: true
          working-directory: platform
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev
          bundle install
      - name: Setup database
        run: |
          bundle exec rails db:create db:schema:load
      - name: Run RuboCop
        run: bundle exec rubocop
      - name: Run RSpec
        run: bundle exec rspec
